# name: auto-point-acquisition / Run python script
name: test-action

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  point-acquisition:
  # run-python-script:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: feature/rakuten

      - name: compose-run
        # env:
        #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build
          docker exec app python main.py

      #-- Slacké€šçŸ¥ --#
      # æˆåŠŸ
      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_USERNAME: auto-deposit-rakuten-horse-racing
          SLACK_TITLE: Success
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ã‚ªãƒ¼ãƒˆãƒ¬ãƒ¼ã‚¹ã«å…¥é‡‘ãŒå®Œäº†ã—ã¾ã—ãŸğŸš€

      # å¤±æ•—
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_USERNAME: auto-deposit-rakuten-horse-racing
          SLACK_TITLE: Failure
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ã‚ªãƒ¼ãƒˆãƒ¬ãƒ¼ã‚¹ã®å…¥é‡‘ãŒå¤±æ•—ã—ã¾ã—ãŸğŸ˜¢

# name: test-action
# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:
# jobs:
#   selenium:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: feature/rakuten
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'
#           architecture: 'x64'
#       - name: run python
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         run: |
#           pip install get-chrome-driver --upgrade
#           pip install -r ./requirements.txt
#           python app/src/main.py