name: auto-point-acquisition

on:
  schedule:
    - cron: "0 1 * * *" # UTCã®1:00ã«å®Ÿè¡Œã™ã‚‹ -> æ—¥æœ¬æ™‚åˆ»ã®åˆå‰10æ™‚
  workflow_dispatch:

env:
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  point-acquisition:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        # with:
        #   ref: feature/point-income

      - name: run auto racing script
        env:
          AUTO_RACE_USER_NUMBER: ${{ secrets.AUTO_RACE_USER_NUMBER }}
          AUTO_RACE_PASSWORD: ${{ secrets.AUTO_RACE_PASSWORD }}
          AUTO_RACE_PIN: ${{ secrets.AUTO_RACE_PIN }}
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build
          docker exec app python ./auto_deposit_autoracing.py

      - name: slack notification on success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_USERNAME: auto-deposit-rakuten-horse-racing
          SLACK_TITLE: Success
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ã‚ªãƒ¼ãƒˆãƒ¬ãƒ¼ã‚¹ã«å…¥é‡‘ãŒå®Œäº†ã—ã¾ã—ãŸğŸš€

      - name: slack notification on failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_USERNAME: auto-deposit-rakuten-horse-racing
          SLACK_TITLE: Failure
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ã‚ªãƒ¼ãƒˆãƒ¬ãƒ¼ã‚¹ã®å…¥é‡‘ãŒå¤±æ•—ã—ã¾ã—ãŸğŸ˜¢
