name: auto-point-acquisition

on:
  schedule:
    - cron: "0 1 * * *" # UTCã®1:00ã«å®Ÿè¡Œã™ã‚‹ -> æ—¥æœ¬æ™‚åˆ»ã®åˆå‰10æ™‚
  workflow_dispatch:

env:
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  auto-point-acquisition:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        # with:
        #   ref: feature/spat4

      - name: set up docker compose
        uses: docker/compose-cli-action@v0.1.1
        with:
          compose-file: docker/docker-compose.yml
          compose-command: up -d --build

      - name: run auto racing script
        env:
          AUTO_RACE_USER_NUMBER: ${{ secrets.AUTO_RACE_USER_NUMBER }}
          AUTO_RACE_PASSWORD: ${{ secrets.AUTO_RACE_PASSWORD }}
          AUTO_RACE_PIN: ${{ secrets.AUTO_RACE_PIN }}
        run: |
          docker exec app python ./auto_deposit_autoracing.py

      - name: run spat4 script
        env:
          SPAT4_MEMBERNUM: ${{ secrets.SPAT4_MEMBERNUM }}
          SPAT4_MEMBERID: ${{ secrets.SPAT4_MEMBERID }}
          SPAT4_MEMBERPASS: ${{ secrets.SPAT4_MEMBERPASS }}
        run: |
          docker exec app python ./auto_deposit_spat4.py

      - name: slack notification on success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_USERNAME: auto-point-acquisition
          SLACK_TITLE: Success
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: è‡ªå‹•å…¥é‡‘ãŒå®Œäº†ã—ã¾ã—ãŸğŸš€

      - name: slack notification on failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_USERNAME: auto-point-acquisition
          SLACK_TITLE: Failure
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: è‡ªå‹•å…¥é‡‘ãŒå¤±æ•—ã—ã¾ã—ãŸğŸ˜¢
