name: test-action

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: Run test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: feature/rakuten

      - name: compose-run
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build
          docker exec app python src/main.py

      # - name: Notify result
      #   uses: 8398a7/action-slack@v3.8.0
      #   with:
      #     status: ${{ job.status }}
      #     author_name: main.pyã®å®Ÿè¡Œçµæœ # è¿½åŠ 
      #     fields: repo,message,commit,author,action,job,took,eventName,ref,workflow
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()

      #-- Slacké€šçŸ¥ --#
      # æˆåŠŸ
      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_TITLE: Deploy / Success
          SLACK_COLOR: good
          SLACK_MESSAGE: ãƒ‡ãƒ—ãƒ­ã‚¤å®Œäº†ã—ã¾ã—ãŸğŸš€

      # å¤±æ•—
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_TITLE: Deploy / Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸğŸ˜¢

# name: test-action
# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:
# jobs:
#   selenium:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: feature/rakuten
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'
#           architecture: 'x64'
#       - name: run python
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         run: |
#           pip install get-chrome-driver --upgrade
#           pip install -r ./requirements.txt
#           python app/src/main.py